package notify

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// hookScript is written to ~/.orion/hooks/claude-notify.sh. It reads Claude's
// hook JSON from stdin and POSTs it to Orion's local hook listener (port from
// ~/.orion/hook-port). Runs in background and exits fast so it doesn't block
// Claude's main loop.
const hookScript = `#!/bin/bash
# Auto-generated by Orion. Forwards Claude Code hook events to Orion's local
# notification listener. Appends tmux_session (from the surrounding tmux) so
# Orion can route a click back to the exact tab.
port_file="$HOME/.orion/hook-port"
[ -r "$port_file" ] || exit 0
port=$(cat "$port_file" 2>/dev/null | tr -d '[:space:]')
[ -z "$port" ] && exit 0
input=$(cat)
[ -z "$input" ] && exit 0
tmux_session=""
if [ -n "${TMUX:-}" ] && command -v tmux >/dev/null 2>&1; then
  tmux_session=$(tmux display-message -p '#{session_name}' 2>/dev/null)
fi
# Inject tmux_session into the JSON blob (best-effort string replace on the
# opening brace). If parsing fails downstream, the raw Claude JSON still
# survives for the notification.
payload="$input"
if [ -n "$tmux_session" ]; then
  payload=$(printf '%s' "$input" | sed "s/^{/{\"tmux_session\":\"$tmux_session\",/")
fi
(printf '%s' "$payload" | curl -sS -m 2 -X POST --data-binary @- "http://127.0.0.1:${port}/hook" >/dev/null 2>&1) &
exit 0
`

// InstallHookScript writes the notification hook script to ~/.orion/hooks/
// and returns its absolute path. Idempotent — only rewrites on content change.
func InstallHookScript() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".orion", "hooks")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "claude-notify.sh")
	existing, _ := os.ReadFile(path)
	if string(existing) != hookScript {
		if err := os.WriteFile(path, []byte(hookScript), 0755); err != nil {
			return "", err
		}
	}
	// Ensure executable bit even if file existed with wrong perms.
	_ = os.Chmod(path, 0755)
	return path, nil
}

// InstallWorkspaceHooks merges Orion's Stop + Notification hooks into
// <workspace>/.claude/settings.local.json (user-local, typically gitignored).
// Existing hooks are preserved; duplicate Orion hooks are not re-added.
func InstallWorkspaceHooks(workspacePath, scriptPath string) error {
	dir := filepath.Join(workspacePath, ".claude")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	path := filepath.Join(dir, "settings.local.json")

	settings := map[string]any{}
	if data, err := os.ReadFile(path); err == nil && len(data) > 0 {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
	}

	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		hooks = map[string]any{}
	}

	for _, event := range []string{"Stop", "Notification"} {
		hooks[event] = mergeHookEvent(hooks[event], scriptPath)
	}
	settings["hooks"] = hooks

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, out, 0644); err != nil {
		return err
	}

	ensureGitignored(workspacePath, ".claude/settings.local.json")
	return nil
}

// mergeHookEvent takes the current value for a hook event (typically an array
// of matcher entries) and appends Orion's hook if not already present.
func mergeHookEvent(existing any, scriptPath string) any {
	entries, _ := existing.([]any)
	orionHook := map[string]any{
		"type":    "command",
		"command": scriptPath,
	}
	// Look for an existing Orion entry (match by command path) and return as-is.
	for _, e := range entries {
		entry, _ := e.(map[string]any)
		hooks, _ := entry["hooks"].([]any)
		for _, h := range hooks {
			hm, _ := h.(map[string]any)
			if hm["command"] == scriptPath {
				return entries
			}
		}
	}
	entries = append(entries, map[string]any{
		"hooks": []any{orionHook},
	})
	return entries
}

// ensureGitignored appends a pattern to the workspace's .gitignore if not
// already present. Best-effort — silent on failure.
func ensureGitignored(workspacePath, pattern string) {
	path := filepath.Join(workspacePath, ".gitignore")
	data, _ := os.ReadFile(path)
	content := string(data)
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimSpace(line) == pattern {
			return
		}
	}
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += pattern + "\n"
	_ = os.WriteFile(path, []byte(content), 0644)
}
