// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateAttachedTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateAttachedTerminal'](arg1, arg2);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function CreateTerminalInDir(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminalInDir'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1, arg2);
}

export function GetAgentTypes(arg1) {
  return window['go']['main']['App']['GetAgentTypes'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetLastProject() {
  return window['go']['main']['App']['GetLastProject']();
}

export function GetProjectInfo(arg1) {
  return window['go']['main']['App']['GetProjectInfo'](arg1);
}

export function GetProjectInfoFromCwd() {
  return window['go']['main']['App']['GetProjectInfoFromCwd']();
}

export function GetSavedTabs() {
  return window['go']['main']['App']['GetSavedTabs']();
}

export function GetServerStatuses(arg1, arg2) {
  return window['go']['main']['App']['GetServerStatuses'](arg1, arg2);
}

export function GetTmuxSession(arg1) {
  return window['go']['main']['App']['GetTmuxSession'](arg1);
}

export function LaunchAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchAgent'](arg1, arg2, arg3);
}

export function LaunchShell(arg1, arg2) {
  return window['go']['main']['App']['LaunchShell'](arg1, arg2);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['App']['ListWorkspaces'](arg1);
}

export function OpenBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenBrowser'](arg1, arg2);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function RecoverSessions(arg1, arg2) {
  return window['go']['main']['App']['RecoverSessions'](arg1, arg2);
}

export function SaveTabs(arg1) {
  return window['go']['main']['App']['SaveTabs'](arg1);
}

export function StartServers(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServers'](arg1, arg2, arg3);
}

export function StopServers(arg1) {
  return window['go']['main']['App']['StopServers'](arg1);
}
