// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocatePorts(arg1, arg2, arg3) {
  return window['go']['main']['App']['AllocatePorts'](arg1, arg2, arg3);
}

export function AnswerClaudeChatRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerClaudeChatRequest'](arg1, arg2, arg3);
}

export function AnswerCodexChatRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerCodexChatRequest'](arg1, arg2, arg3);
}

export function ApproveClaudePlan(arg1) {
  return window['go']['main']['App']['ApproveClaudePlan'](arg1);
}

export function ApproveCodexPlan(arg1) {
  return window['go']['main']['App']['ApproveCodexPlan'](arg1);
}

export function AttachClaudeChat(arg1, arg2) {
  return window['go']['main']['App']['AttachClaudeChat'](arg1, arg2);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConvertChatToTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertChatToTerminal'](arg1, arg2, arg3, arg4);
}

export function ConvertTerminalToClaudeChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertTerminalToClaudeChat'](arg1, arg2, arg3);
}

export function ConvertTerminalToCodexChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertTerminalToCodexChat'](arg1, arg2, arg3);
}

export function CreateAttachedTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateAttachedTerminal'](arg1, arg2);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function CreateTerminalInDir(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminalInDir'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function CreateWorkspaceFrom(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceFrom'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1, arg2);
}

export function DetachTerminal(arg1) {
  return window['go']['main']['App']['DetachTerminal'](arg1);
}

export function DiscardAllChanges(arg1) {
  return window['go']['main']['App']['DiscardAllChanges'](arg1);
}

export function DiscardFileChanges(arg1, arg2) {
  return window['go']['main']['App']['DiscardFileChanges'](arg1, arg2);
}

export function EmitSessionCreated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EmitSessionCreated'](arg1, arg2, arg3, arg4);
}

export function EmitSessionCreatedInfo(arg1) {
  return window['go']['main']['App']['EmitSessionCreatedInfo'](arg1);
}

export function GetAgentNames(arg1) {
  return window['go']['main']['App']['GetAgentNames'](arg1);
}

export function GetAgentTypes(arg1) {
  return window['go']['main']['App']['GetAgentTypes'](arg1);
}

export function GetChangedFiles(arg1) {
  return window['go']['main']['App']['GetChangedFiles'](arg1);
}

export function GetChangedFilesAgainst(arg1, arg2) {
  return window['go']['main']['App']['GetChangedFilesAgainst'](arg1, arg2);
}

export function GetClaudeChatMessages(arg1) {
  return window['go']['main']['App']['GetClaudeChatMessages'](arg1);
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetCodexChatMessages(arg1) {
  return window['go']['main']['App']['GetCodexChatMessages'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2);
}

export function GetLastProject() {
  return window['go']['main']['App']['GetLastProject']();
}

export function GetMemorySnapshot() {
  return window['go']['main']['App']['GetMemorySnapshot']();
}

export function GetMobileToken() {
  return window['go']['main']['App']['GetMobileToken']();
}

export function GetMobileURL() {
  return window['go']['main']['App']['GetMobileURL']();
}

export function GetProjectInfo(arg1) {
  return window['go']['main']['App']['GetProjectInfo'](arg1);
}

export function GetProjectInfoFromCwd() {
  return window['go']['main']['App']['GetProjectInfoFromCwd']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSavedTabs() {
  return window['go']['main']['App']['GetSavedTabs']();
}

export function GetServerStatuses(arg1, arg2) {
  return window['go']['main']['App']['GetServerStatuses'](arg1, arg2);
}

export function GetTmuxSession(arg1) {
  return window['go']['main']['App']['GetTmuxSession'](arg1);
}

export function GetUnifiedDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetUnifiedDiff'](arg1, arg2, arg3);
}

export function GetWorkspaceEnv(arg1) {
  return window['go']['main']['App']['GetWorkspaceEnv'](arg1);
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function LaunchAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchAgent'](arg1, arg2, arg3);
}

export function LaunchClaudeChat(arg1, arg2) {
  return window['go']['main']['App']['LaunchClaudeChat'](arg1, arg2);
}

export function LaunchCodexChat(arg1, arg2) {
  return window['go']['main']['App']['LaunchCodexChat'](arg1, arg2);
}

export function LaunchCodexChatWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LaunchCodexChatWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function LaunchShell(arg1, arg2) {
  return window['go']['main']['App']['LaunchShell'](arg1, arg2);
}

export function ListClaudeChatSessions(arg1) {
  return window['go']['main']['App']['ListClaudeChatSessions'](arg1);
}

export function ListCodexChatSessions(arg1) {
  return window['go']['main']['App']['ListCodexChatSessions'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['App']['ListWorkspaces'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function NewWindowWithProject(arg1) {
  return window['go']['main']['App']['NewWindowWithProject'](arg1);
}

export function OpenBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenBrowser'](arg1, arg2);
}

export function OpenChatAttachmentDialog() {
  return window['go']['main']['App']['OpenChatAttachmentDialog']();
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function ReadFileContents(arg1) {
  return window['go']['main']['App']['ReadFileContents'](arg1);
}

export function RecoverSessions(arg1, arg2) {
  return window['go']['main']['App']['RecoverSessions'](arg1, arg2);
}

export function ResumeClaudeChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeClaudeChat'](arg1, arg2, arg3);
}

export function ResumeCodexChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeCodexChat'](arg1, arg2, arg3);
}

export function ResumeCodexChatWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ResumeCodexChatWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveTabs(arg1) {
  return window['go']['main']['App']['SaveTabs'](arg1);
}

export function SearchContents(arg1, arg2) {
  return window['go']['main']['App']['SearchContents'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SendClaudeChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendClaudeChatMessage'](arg1, arg2, arg3);
}

export function SendCodexChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCodexChatMessage'](arg1, arg2, arg3);
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function StartServers(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServers'](arg1, arg2, arg3);
}

export function StopClaudeChat(arg1) {
  return window['go']['main']['App']['StopClaudeChat'](arg1);
}

export function StopCodexChat(arg1) {
  return window['go']['main']['App']['StopCodexChat'](arg1);
}

export function StopServers(arg1) {
  return window['go']['main']['App']['StopServers'](arg1);
}

export function WatchWorkspace(arg1) {
  return window['go']['main']['App']['WatchWorkspace'](arg1);
}
