// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocatePorts(arg1, arg2, arg3) {
  return window['go']['main']['App']['AllocatePorts'](arg1, arg2, arg3);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateAttachedTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateAttachedTerminal'](arg1, arg2);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function CreateTerminalInDir(arg1, arg2) {
  return window['go']['main']['App']['CreateTerminalInDir'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteWorkspace(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1, arg2);
}

export function GetAgentTypes(arg1) {
  return window['go']['main']['App']['GetAgentTypes'](arg1);
}

export function GetChangedFiles(arg1) {
  return window['go']['main']['App']['GetChangedFiles'](arg1);
}

export function GetChangedFilesAgainst(arg1, arg2) {
  return window['go']['main']['App']['GetChangedFilesAgainst'](arg1, arg2);
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2);
}

export function GetLastProject() {
  return window['go']['main']['App']['GetLastProject']();
}

export function GetProjectInfo(arg1) {
  return window['go']['main']['App']['GetProjectInfo'](arg1);
}

export function GetProjectInfoFromCwd() {
  return window['go']['main']['App']['GetProjectInfoFromCwd']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetSavedTabs() {
  return window['go']['main']['App']['GetSavedTabs']();
}

export function GetServerStatuses(arg1, arg2) {
  return window['go']['main']['App']['GetServerStatuses'](arg1, arg2);
}

export function GetTmuxSession(arg1) {
  return window['go']['main']['App']['GetTmuxSession'](arg1);
}

export function GetUnifiedDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetUnifiedDiff'](arg1, arg2, arg3);
}

export function GetWorkspaceEnv(arg1) {
  return window['go']['main']['App']['GetWorkspaceEnv'](arg1);
}

export function LaunchAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchAgent'](arg1, arg2, arg3);
}

export function LaunchShell(arg1, arg2) {
  return window['go']['main']['App']['LaunchShell'](arg1, arg2);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function ListTerminals() {
  return window['go']['main']['App']['ListTerminals']();
}

export function ListWorkspaces(arg1) {
  return window['go']['main']['App']['ListWorkspaces'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function NewWindowWithProject(arg1) {
  return window['go']['main']['App']['NewWindowWithProject'](arg1);
}

export function OpenBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenBrowser'](arg1, arg2);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function ReadFileContents(arg1) {
  return window['go']['main']['App']['ReadFileContents'](arg1);
}

export function RecoverSessions(arg1, arg2) {
  return window['go']['main']['App']['RecoverSessions'](arg1, arg2);
}

export function SaveTabs(arg1) {
  return window['go']['main']['App']['SaveTabs'](arg1);
}

export function SearchContents(arg1, arg2) {
  return window['go']['main']['App']['SearchContents'](arg1, arg2);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2);
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function StartServers(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServers'](arg1, arg2, arg3);
}

export function StopServers(arg1) {
  return window['go']['main']['App']['StopServers'](arg1);
}
