// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {claudesdk} from '../models';
import {codexchat} from '../models';
import {state} from '../models';
import {plugin} from '../models';
import {web} from '../models';
import {main} from '../models';
import {git} from '../models';
import {config} from '../models';
import {diag} from '../models';
import {server} from '../models';
import {files} from '../models';
import {chatattachments} from '../models';

export function AdoptWorkspace(arg1:string):Promise<workspace.Workspace>;

export function AllocatePorts(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function AnswerClaudeChatRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AnswerCodexChatRequest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ApproveClaudePlan(arg1:string):Promise<void>;

export function ApproveCodexPlan(arg1:string):Promise<void>;

export function AttachClaudeChat(arg1:string,arg2:string):Promise<claudesdk.SessionInfo>;

export function CleanupAdoptedWorkspace(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConvertChatToTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ConvertChatToTerminalWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function ConvertTerminalToClaudeChat(arg1:string,arg2:string,arg3:string):Promise<claudesdk.SessionInfo>;

export function ConvertTerminalToClaudeChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<claudesdk.SessionInfo>;

export function ConvertTerminalToCodexChat(arg1:string,arg2:string,arg3:string):Promise<codexchat.SessionInfo>;

export function ConvertTerminalToCodexChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<codexchat.SessionInfo>;

export function CreateAttachedTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateTerminal(arg1:string):Promise<void>;

export function CreateTerminalInDir(arg1:string,arg2:string):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function CreateWorkspaceFrom(arg1:string,arg2:string,arg3:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string,arg2:string):Promise<void>;

export function DetachTerminal(arg1:string):Promise<void>;

export function DiscardAllChanges(arg1:string):Promise<void>;

export function DiscardFileChanges(arg1:string,arg2:string):Promise<void>;

export function EmitSessionCreated(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EmitSessionCreatedInfo(arg1:state.SessionInfo):Promise<void>;

export function EmitSessionKilled(arg1:string):Promise<void>;

export function EmitWorkspaceCreated(arg1:string,arg2:workspace.Workspace):Promise<void>;

export function EmitWorkspaceDeleted(arg1:string,arg2:string):Promise<void>;

export function FormatFile(arg1:string,arg2:string,arg3:string):Promise<plugin.FormatResult>;

export function GetAgentNames(arg1:string):Promise<Array<web.AgentType>>;

export function GetAgentTypes(arg1:string):Promise<Array<main.AgentTypeInfo>>;

export function GetChangedFiles(arg1:string):Promise<Array<git.ChangedFile>>;

export function GetChangedFilesAgainst(arg1:string,arg2:string):Promise<Array<git.ChangedFile>>;

export function GetClaudeChatMessages(arg1:string):Promise<Array<claudesdk.Message>>;

export function GetClipboard():Promise<string>;

export function GetCodexChatMessages(arg1:string):Promise<Array<codexchat.Message>>;

export function GetConfig(arg1:string):Promise<config.OrionConfig>;

export function GetFileDiff(arg1:string,arg2:string):Promise<git.FileDiff>;

export function GetFormatOnSaveExtensions(arg1:string):Promise<Array<string>>;

export function GetGitStatus(arg1:string):Promise<git.RepositoryStatus>;

export function GetLastProject():Promise<string>;

export function GetMemorySnapshot():Promise<diag.MemorySnapshot>;

export function GetMobileToken():Promise<string>;

export function GetMobileURL():Promise<string>;

export function GetProjectInfo(arg1:string):Promise<workspace.ProjectInfo>;

export function GetProjectInfoFromCwd():Promise<workspace.ProjectInfo>;

export function GetRecentProjects():Promise<Array<string>>;

export function GetSavedTabs():Promise<Array<state.SavedTab>>;

export function GetServerStatuses(arg1:string,arg2:string):Promise<Array<server.ServerStatus>>;

export function GetTmuxSession(arg1:string):Promise<string>;

export function GetUnifiedDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetWorkspaceEnv(arg1:string):Promise<Record<string, string>>;

export function GitFetch(arg1:string):Promise<git.ActionResult>;

export function GitPull(arg1:string):Promise<git.ActionResult>;

export function GitPush(arg1:string):Promise<git.ActionResult>;

export function IsLSPRunning(arg1:string):Promise<boolean>;

export function IsTerminalBusy(arg1:string):Promise<boolean>;

export function KillSession(arg1:string):Promise<void>;

export function LaunchAgent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LaunchClaudeChat(arg1:string,arg2:string):Promise<claudesdk.SessionInfo>;

export function LaunchClaudeChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<claudesdk.SessionInfo>;

export function LaunchCodexChat(arg1:string,arg2:string):Promise<codexchat.SessionInfo>;

export function LaunchCodexChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<codexchat.SessionInfo>;

export function LaunchShell(arg1:string,arg2:string):Promise<string>;

export function LintFile(arg1:string,arg2:string):Promise<plugin.LintResult>;

export function ListBaseRefs(arg1:string):Promise<workspace.BaseRefs>;

export function ListClaudeChatHistory(arg1:string,arg2:number):Promise<Array<claudesdk.HistoryThread>>;

export function ListClaudeChatSessions(arg1:Array<string>):Promise<Array<state.SessionInfo>>;

export function ListCodexChatHistory(arg1:string,arg2:number):Promise<Array<codexchat.HistoryThread>>;

export function ListCodexChatSessions(arg1:Array<string>):Promise<Array<state.SessionInfo>>;

export function ListDirectory(arg1:string,arg2:number):Promise<Array<files.FileEntry>>;

export function ListLSPServers():Promise<Array<string>>;

export function ListTerminals():Promise<Array<string>>;

export function ListWorkspaces(arg1:string):Promise<Array<workspace.Workspace>>;

export function LogClient(arg1:string,arg2:string):Promise<void>;

export function LogPath():Promise<string>;

export function NewWindow():Promise<void>;

export function NewWindowWithProject(arg1:string):Promise<void>;

export function OpenBrowser(arg1:string,arg2:string):Promise<void>;

export function OpenChatAttachmentDialog():Promise<Array<chatattachments.Attachment>>;

export function OpenProjectDialog():Promise<workspace.ProjectInfo>;

export function ReadFileContents(arg1:string):Promise<string>;

export function RecoverSessions(arg1:string,arg2:Array<string>):Promise<Array<state.SessionInfo>>;

export function ResumeClaudeChat(arg1:string,arg2:string,arg3:string):Promise<claudesdk.SessionInfo>;

export function ResumeClaudeChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<claudesdk.SessionInfo>;

export function ResumeCodexChat(arg1:string,arg2:string,arg3:string):Promise<codexchat.SessionInfo>;

export function ResumeCodexChatWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<codexchat.SessionInfo>;

export function RevealInFinder(arg1:string):Promise<void>;

export function RunOnSave(arg1:string,arg2:string):Promise<Array<string>>;

export function SaveTabs(arg1:Array<state.SavedTab>):Promise<void>;

export function SaveWorkspaceOrder(arg1:Array<string>):Promise<void>;

export function SearchContents(arg1:string,arg2:string):Promise<Array<files.GrepResult>>;

export function SearchFiles(arg1:string,arg2:string):Promise<Array<files.SearchResult>>;

export function SendClaudeChatMessage(arg1:string,arg2:string,arg3:Array<chatattachments.Attachment>):Promise<void>;

export function SendCodexChatMessage(arg1:string,arg2:string,arg3:Array<chatattachments.Attachment>):Promise<void>;

export function SendLSPMessage(arg1:string,arg2:string):Promise<void>;

export function SendLSPRequest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetActiveProject(arg1:string):Promise<void>;

export function SetClipboard(arg1:string):Promise<void>;

export function StartLSP(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartServers(arg1:string,arg2:string,arg3:boolean):Promise<Array<server.ServerStatus>>;

export function StopClaudeChat(arg1:string):Promise<void>;

export function StopCodexChat(arg1:string):Promise<void>;

export function StopLSP(arg1:string):Promise<void>;

export function StopServers(arg1:string):Promise<void>;

export function WatchWorkspace(arg1:string):Promise<void>;

export function WriteFileContents(arg1:string,arg2:string):Promise<void>;
