// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {main} from '../models';
import {config} from '../models';
import {state} from '../models';
import {server} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateAttachedTerminal(arg1:string,arg2:string):Promise<void>;

export function CreateTerminal(arg1:string):Promise<void>;

export function CreateTerminalInDir(arg1:string,arg2:string):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string,arg2:string):Promise<void>;

export function GetAgentTypes(arg1:string):Promise<Array<main.AgentTypeInfo>>;

export function GetConfig(arg1:string):Promise<config.OrionConfig>;

export function GetLastProject():Promise<string>;

export function GetProjectInfo(arg1:string):Promise<workspace.ProjectInfo>;

export function GetProjectInfoFromCwd():Promise<workspace.ProjectInfo>;

export function GetSavedTabs():Promise<Array<state.SavedTab>>;

export function GetServerStatuses(arg1:string,arg2:string):Promise<Array<server.ServerStatus>>;

export function GetTmuxSession(arg1:string):Promise<string>;

export function LaunchAgent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LaunchShell(arg1:string,arg2:string):Promise<string>;

export function ListTerminals():Promise<Array<string>>;

export function ListWorkspaces(arg1:string):Promise<Array<workspace.Workspace>>;

export function OpenBrowser(arg1:string,arg2:string):Promise<void>;

export function OpenProjectDialog():Promise<workspace.ProjectInfo>;

export function RecoverSessions(arg1:string,arg2:Array<string>):Promise<Array<state.SessionInfo>>;

export function SaveTabs(arg1:Array<state.SavedTab>):Promise<void>;

export function StartServers(arg1:string,arg2:string,arg3:boolean):Promise<Array<server.ServerStatus>>;

export function StopServers(arg1:string):Promise<void>;
